### ISSUE TITLE
v1.4.0 is not compatible with Joomla 4

### ISSUE THREAD

**Issue by ragues** [SharkyKZ/plg_system_removegenerator#2]
Attempting to install v1.4.0 in Joomla 4 (4.1.0) generates the error

_Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin()_

and blocks access to the system dashboard.

At least _JROOT/plugins/system/extremovehtml/extremovehtml.php:19_ is involved.

**Comment by SharkyKZ** [comment]
Hello. The error is coming from a different extension. Judging by the name, it's this one https://extensions.joomla.org/extension/ext-remove-html-code/. If so, their support is here http://eco-joom.com/en/support.html.

Closing this.
